variables:
  - name: aks-container-deployment_name
    type: string
    description: The name of the resource group
  - name: azure-storage-blob_storage_account_name
    type: string
    description: The name of the Azure Storage Account
  - name: blob_resource_group_name
    type: string
    description: The name of the resource group
  - name: client_id
    type: string
  - name: config_banner_text
    type: string
    description: The text that will appear in the top banner in the cluster
  - name: data-hub-connection_name
    type: string
    description: The name of the resource group
  - name: databricks-workspace_name
    type: string
    description: The name of the resource group
  - name: gitops_repo_repo
    type: string
    description: The short name of the repository (i.e. the part after the org/group name)
  - name: inbound-internet-connection_name
    type: string
    description: The name of the resource group
  - name: integration-services-connection_name
    type: string
    description: The name of the resource group
  - name: oracle-database-connection_name
    type: string
    description: The name of the resource group
  - name: region
    type: string
    description: The Azure location where the resource group will be provisioned
  - name: resource_group_name
    type: string
    description: The name of the resource group
  - name: salesforce-connection_name
    type: string
    description: The name of the resource group
  - name: self-hosted-integration-runtime_name
    type: string
    description: The name of the resource group
  - name: subscription_id
    type: string
  - name: tenant_id
    type: string
  - name: teradata-connection_name
    type: string
    description: The name of the resource group
  - name: gitops_repo_host
    type: string
    description: >-
      The host for the git repository. The git host used can be a GitHub, GitHub
      Enterprise, Gitlab, Bitbucket, Gitea or Azure DevOps server. If the host
      is null assumes in-cluster Gitea instance will be used.
    value: ''
  - name: gitops_repo_org
    type: string
    description: >-
      The org/group where the git repository exists/will be provisioned. If the
      value is left blank then the username org will be used.
    value: ''
  - name: gitops_repo_project
    type: string
    description: >-
      The project that will be used for the git repo. (Primarily used for Azure
      DevOps repos)
    value: ''
  - name: gitops_repo_username
    type: string
    description: The username of the user with access to the repository
    value: ''
  - name: name_prefix
    type: string
    description: The name of the vpc resource
    value: ''
  - name: pull_secret
    type: string
    description: >-
      The contents of the pull secret needed to access Red Hat content. The
      contents can either be provided directly or passed through the
      `pull_secret_file` variable
    value: ''
  - name: pull_secret_file
    type: string
    description: >-
      Name of the file containing the pull secret needed to access Red Hat
      content. The contents can either be provided in this file or directly via
      the `pull_secret` variable
    value: ''
